# Generated by Django 3.2.5 on 2021-07-11 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('task_type', models.CharField(blank=True, choices=[('survey', 'survey'), ('discussion', 'discussion'), ('diary', 'diary')], max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_date', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('live', 'live'), ('pending', 'pending'), ('archived', 'archived')], max_length=10, null=True)),
                ('tasks', models.ManyToManyField(to='myapp.Task')),
            ],
        ),
    ]
